repos:
  - repo: builtin
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-case-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-symlinks
      - id: fix-byte-order-marker
      - id: detect-private-key
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.10
    hooks:
      - id: ruff-check
      - id: ruff-format
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.7
    hooks:
      - id: uv-lock
      - id: uv-audit
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.24.1
    hooks:
      - id: zizmor
        args: [--no-progress, --offline, --persona=auditor]
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck
        args: [--external-sources]
        exclude: ^compose/scripts/cli-(zsh-)?autocomplete\.sh$
  - repo: local
    hooks:
      - id: oxfmt
        name: oxfmt
        types: [text]
        language: node
        require_serial: true
        entry: npx oxfmt --no-error-on-unmatched-pattern
      - id: docker-shell-shfmt
        name: Run shfmt with docker
        entry: mvdan/shfmt:latest -d -i 4
        language: docker_image
        types: [shell]
        exclude: compose/scripts/cli-zsh-autocomplete.sh
      - id: generate-images
        name: Generate docker images
        entry: compose/scripts/generate-templates.sh
        language: system
        files: >-
          ^compose/Dockerfile-coin.template$
