#!/usr/bin/env bash
source generator-env.sh

BITCARTGEN_DOCKER_IMAGE='mrnaif/docker-compose-generator'

docker run -v "$PWD/compose:/app/compose" \
    -e "BITCART_INSTALL=${BITCART_INSTALL:-all}" \
    -e "BITCART_CRYPTO1=${BITCART_CRYPTO1:-btc}" \
    -e "BITCART_CRYPTO2=$BITCART_CRYPTO2" \
    -e "BITCART_CRYPTO3=$BITCART_CRYPTO3" \
    -e "BITCART_CRYPTO4=$BITCART_CRYPTO4" \
    -e "BITCART_CRYPTO5=$BITCART_CRYPTO5" \
    -e "BITCART_CRYPTO6=$BITCART_CRYPTO6" \
    -e "BITCART_CRYPTO7=$BITCART_CRYPTO7" \
    -e "BITCART_CRYPTO8=$BITCART_CRYPTO8" \
    -e "BITCART_CRYPTO9=$BITCART_CRYPTO9" \
    -e "BITCART_REVERSEPROXY=${BITCART_REVERSEPROXY:-nginx-https}" \
    -e "BITCART_ADDITIONAL_COMPONENTS=$BITCART_ADDITIONAL_COMPONENTS" \
    $BITCARTGEN_DOCKER_IMAGE