bitcart_update_docker_env() {
touch $BITCART_ENV_FILE
cat > $BITCART_ENV_FILE << EOF
BITCART_HOST=$BITCART_HOST
BITCART_LETSENCRYPT_EMAIL=$BITCART_LETSENCRYPT_EMAIL
BITCART_FRONTEND_HOST=$BITCART_FRONTEND_HOST
BITCART_FRONTEND_URL=$BITCART_FRONTEND_URL
BITCART_FRONTEND_EMAIL=$BITCART_FRONTEND_EMAIL
BITCART_FRONTEND_PASSWORD=$BITCART_FRONTEND_PASSWORD
BITCART_FRONTEND_STORE=$BITCART_FRONTEND_STORE
BITCART_ADMIN_HOST=$BITCART_ADMIN_HOST
BITCART_ADMIN_URL=$BITCART_ADMIN_URL
BITCART_CRYPTOS=${BITCART_CRYPTOS:-btc}
BTC_NETWORK=$BTC_NETWORK
BTC_LIGHTNING=$BTC_LIGHTNING
BCH_NETWORK=$BCH_NETWORK
LTC_NETWORK=$LTC_NETWORK
LTC_LIGHTNING=$LTC_LIGHTNING
GZRO_NETWORK=$GZRO_NETWORK
GZRO_LIGHTNING=$GZRO_LIGHTNING
BSTY_NETWORK=$BSTY_NETWORK
BSTY_LIGHTNING=$BSTY_LIGHTNING
$(env | awk -F "=" '{print "\n"$0}' | grep "BITCART_.*.*_PORT")
EOF
}