services:
  admin:
    restart: unless-stopped
    image: bitcartcc/bitcart-admin:stable
    expose:
      - "4000"
    command: yarn start
    environment:
      BITCART_ADMIN_LOG_FILE: bitcart.log
      BITCART_ADMIN_API_URL: ${BITCART_ADMIN_API_URL}
      VIRTUAL_NETWORK: nginx-proxy
      VIRTUAL_PORT: 4000
      VIRTUAL_HOST: ${BITCART_ADMIN_HOST}
      VIRTUAL_HOST_NAME: "bitcart-admin"
      LETSENCRYPT_HOST: ${BITCART_ADMIN_HOST}
      LETSENCRYPT_EMAIL: ${BITCART_LETSENCRYPT_EMAIL:-<no value>}
      BITCART_ADMIN_ROOTPATH: ${BITCART_ADMIN_ROOTPATH:-/}
