services:
  backend:
    restart: unless-stopped
    image: bitcart/bitcart:stable
    command: bash -c "alembic upgrade head && gunicorn -c gunicorn.conf.py main:app"
    environment:
      LOG_FILE: bitcart.log
      BITCART_DATADIR: /datadir
      BITCART_BACKUPS_DIR: /backups
      BITCART_VOLUMES: /datadir /backups /plugins
      DB_PORT: 5432
      DB_HOST: database
      VIRTUAL_NETWORK: nginx-proxy
      VIRTUAL_PORT: 8000
      VIRTUAL_HOST: ${BITCART_HOST}
      VIRTUAL_HOST_NAME: "bitcart-backend"
      LETSENCRYPT_HOST: ${BITCART_HOST}
      LETSENCRYPT_EMAIL: ${BITCART_LETSENCRYPT_EMAIL}
      BITCART_CRYPTOS: ${BITCART_CRYPTOS:-btc}
      BTC_NETWORK: ${BTC_NETWORK:-mainnet}
      BTC_LIGHTNING: ${BTC_LIGHTNING:-false}
      BCH_NETWORK: ${BCH_NETWORK:-mainnet}
      ETH_NETWORK: ${ETH_NETWORK:-mainnet}
      BNB_NETWORK: ${BNB_NETWORK:-mainnet}
      SBCH_NETWORK: ${SBCH_NETWORK:-mainnet}
      MATIC_NETWORK: ${MATIC_NETWORK:-mainnet}
      TRX_NETWORK: ${TRX_NETWORK:-mainnet}
      XRG_NETWORK: ${XRG_NETWORK:-mainnet}
      LTC_NETWORK: ${LTC_NETWORK:-mainnet}
      LTC_LIGHTNING: ${LTC_LIGHTNING:-false}
      BSTY_NETWORK: ${BSTY_NETWORK:-mainnet}
      BSTY_LIGHTNING: ${BSTY_LIGHTNING:-false}
      GRS_NETWORK: ${GRS_NETWORK:-mainnet}
      GRS_LIGHTNING: ${GRS_LIGHTNING:-false}
      XMR_NETWORK: ${XMR_NETWORK:-mainnet}
      UPDATE_URL: ${BITCART_UPDATE_URL:-https://api.bitcart.ai/updates/latest}
      BITCART_BACKEND_ROOTPATH: ${BITCART_BACKEND_ROOTPATH:-}
      SSH_CONNECTION: "root@host.docker.internal:$<BITCART_SSH_PORT>:22?"
      SSH_KEY_FILE: ${BITCART_SSH_KEY_FILE}
      SSH_AUTHORIZED_KEYS: ${BITCART_SSH_AUTHORIZED_KEYS}
      BASH_PROFILE_SCRIPT: ${BASH_PROFILE_SCRIPT}
      BITCART_BACKEND_PLUGINS_DIR: /plugins/backend
      BITCART_ADMIN_PLUGINS_DIR: /plugins/admin
      BITCART_STORE_PLUGINS_DIR: /plugins/store
      BITCART_DOCKER_PLUGINS_DIR: /plugins/docker
      BITCART_HOST: ${BITCART_HOST}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    expose:
      - "8000"
    volumes:
      - "bitcart_datadir:/datadir"
      - "backup_datadir:/backups"
      - "./plugins/backend:/plugins/backend"
      - "./plugins/admin:/plugins/admin"
      - "./plugins/store:/plugins/store"
      - "./plugins/docker:/plugins/docker"
      - "$<BITCART_HOST_SSH_AUTHORIZED_KEYS>?:${BITCART_SSH_AUTHORIZED_KEYS}"

  worker:
    depends_on:
      - backend
    links:
      - backend

volumes:
  bitcart_datadir:
  backup_datadir:
    external: true
