services:
  binancecoin:
    restart: unless-stopped
    image: bitcart/bitcart-bnb:stable
    environment:
      BNB_NETWORK: ${BNB_NETWORK:-mainnet}
      BNB_SERVER: ${BNB_SERVER:-https://seed-server.bitcart.ai}
      BNB_SEED_SERVER: ${BNB_SEED_SERVER:-https://seed-server.bitcart.ai}
      BNB_ARCHIVE_SERVER: ${BNB_ARCHIVE_SERVER:-}
      BNB_DEBUG: ${BNB_DEBUG:-false}
    expose:
      - "5006"
    volumes:
      - "binancecoin_datadir:/data"

  backend:
    depends_on:
      - binancecoin
    links:
      - binancecoin

volumes:
  binancecoin_datadir:
