services:
  cloudflared:
    container_name: cloudflared-tunnel
    image: bitcartcc/cloudflared:2022.7.1
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    restart: on-failure
    depends_on:
      - nginx
    links:
      - nginx
