services:
  ergon:
    restart: unless-stopped
    image: bitcart/bitcart-xrg:stable
    environment:
      XRG_NETWORK: ${XRG_NETWORK:-mainnet}
      XRG_DEBUG: ${XRG_DEBUG:-false}
    expose:
      - "5005"
    volumes:
      - "ergon_datadir:/data"

  backend:
    depends_on:
      - ergon
    links:
      - ergon

volumes:
  ergon_datadir:
