services:
  ethereum:
    restart: unless-stopped
    image: bitcart/bitcart-eth:stable
    environment:
      ETH_NETWORK: ${ETH_NETWORK:-mainnet}
      ETH_SERVER: ${ETH_SERVER:-https://mainnet.infura.io/v3/b6bf7d3508c941499b10025c0776eaf8}
      ETH_ARCHIVE_SERVER: ${ETH_ARCHIVE_SERVER:-}
      ETH_DEBUG: ${ETH_DEBUG:-false}
    expose:
      - "5002"
    volumes:
      - "ethereum_datadir:/data"

  backend:
    depends_on:
      - ethereum
    links:
      - ethereum

volumes:
  ethereum_datadir:
