services:
  ethereum:
    restart: unless-stopped
    image: bitcart/bitcart-eth:stable
    environment:
      ETH_NETWORK: ${ETH_NETWORK:-mainnet}
      ETH_SERVER: ${ETH_SERVER:-https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161}
      ETH_DEBUG: ${ETH_DEBUG:-false}
    expose:
      - "5002"
    volumes:
      - "ethereum_datadir:/data"

  backend:
    depends_on:
      - ethereum
    links:
      - ethereum

volumes:
  ethereum_datadir:
