services:
  groestlcoin:
    restart: unless-stopped
    image: bitcart/bitcart-grs:stable
    environment:
      GRS_NETWORK: ${GRS_NETWORK:-mainnet}
      GRS_LIGHTNING: ${GRS_LIGHTNING:-false}
      GRS_LIGHTNING_GOSSIP: ${GRS_LIGHTNING_GOSSIP:-false}
      GRS_DEBUG: ${GRS_DEBUG:-false}
    expose:
      - "5010"
    volumes:
      - "groestlcoin_datadir:/data"

  backend:
    depends_on:
      - groestlcoin
    links:
      - groestlcoin

volumes:
  groestlcoin_datadir:
