services:
  monero:
    restart: unless-stopped
    image: bitcartcc/bitcart-xmr:stable
    environment:
      XMR_NETWORK: ${XMR_NETWORK:-mainnet}
      XMR_SERVER: ${XMR_SERVER:-http://node.community.rino.io:18081}
      XMR_DEBUG: ${XMR_DEBUG:-false}
    expose:
      - "5011"
    volumes:
      - "monero_datadir:/data"

  backend:
    depends_on:
      - monero
    links:
      - monero

volumes:
  monero_datadir:
