services:
  nginx-https:
    restart: unless-stopped
    image: nginxproxy/acme-companion:2.1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "nginx_conf:/etc/nginx/conf.d"
      - "nginx_vhost:/etc/nginx/vhost.d"
      - "nginx_html:/usr/share/nginx/html"
      - "acme:/etc/acme.sh"
      - "nginx_certs:/etc/nginx/certs:rw"
    environment:
      ACME_CA_URI: ${ACME_CA_URI:-https://acme-v02.api.letsencrypt.org/directory}
    links:
      - nginx-gen

  nginx:
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  nginx-gen:
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen

volumes:
  acme:
