services:
  nginx-gen:
    environment:
      HTTPS_ENABLED: "true"

  nginx-https:
    restart: unless-stopped
    image: nginxproxy/acme-companion:2.6
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "nginx_conf:/etc/nginx/conf.d"
      - "nginx_html:/usr/share/nginx/html"
      - "nginx_certs:/etc/nginx/certs:rw"
      - "acme:/etc/acme.sh"
    environment:
      NGINX_DOCKER_GEN_CONTAINER: "$<DEPLOYENT_NAME>?-nginx-gen-1"
      NGINX_PROXY_CONTAINER: "$<DEPLOYENT_NAME>?-nginx-1"
      ACME_CA_URI: ${ACME_CA_URI:-https://acme-v02.api.letsencrypt.org/directory}
    links:
      - nginx-gen

volumes:
  acme:
