services:
  nginx:
    restart: unless-stopped
    image: nginx:stable
    ports:
      - "${REVERSEPROXY_HTTP_PORT:-80}:80"
      - "${REVERSEPROXY_HTTPS_PORT:-443}:443"
    volumes:
      - "nginx_conf:/etc/nginx/conf.d"
      - "nginx_vhost:/etc/nginx/vhost.d"
      - "nginx_html:/usr/share/nginx/html"
      - "nginx_certs:/etc/nginx/certs:ro"
    labels:
      - org.bitcartcc.nginx=true

  nginx-gen:
    restart: unless-stopped
    image: bitcartcc/docker-gen:0.9.1
    environment:
      DEFAULT_HOST: ${REVERSEPROXY_DEFAULT_HOST:-none}
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
      - "nginx_conf:/etc/nginx/conf.d"
      - "nginx_vhost:/etc/nginx/vhost.d"
      - "nginx_html:/usr/share/nginx/html"
      - "nginx_certs:/etc/nginx/certs:ro"
    entrypoint: /usr/local/bin/docker-gen -notify-sighup label=org.bitcartcc.nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    links:
      - nginx

volumes:
  nginx_conf:
  nginx_vhost:
  nginx_html:
  nginx_certs:
