services:
  polygon:
    restart: unless-stopped
    image: bitcart/bitcart-matic:stable
    environment:
      MATIC_NETWORK: ${MATIC_NETWORK:-mainnet}
      MATIC_SERVER: ${MATIC_SERVER:-https://seed-server.bitcart.ai}
      MATIC_SEED_SERVER: ${MATIC_SEED_SERVER:-https://seed-server.bitcart.ai}
      MATIC_ARCHIVE_SERVER: ${MATIC_ARCHIVE_SERVER:-}
      MATIC_DEBUG: ${MATIC_DEBUG:-false}
    expose:
      - "5008"
    volumes:
      - "polygon_datadir:/data"

  backend:
    depends_on:
      - polygon
    links:
      - polygon

volumes:
  polygon_datadir:
