services:
  polygon:
    restart: unless-stopped
    image: bitcart/bitcart-matic:stable
    environment:
      MATIC_NETWORK: ${MATIC_NETWORK:-mainnet}
      MATIC_SERVER: ${MATIC_SERVER:-https://polygon-mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161}
      MATIC_DEBUG: ${MATIC_DEBUG:-false}
    expose:
      - "5008"
    volumes:
      - "polygon_datadir:/data"

  backend:
    depends_on:
      - polygon
    links:
      - polygon

volumes:
  polygon_datadir:
