services:
  database:
    restart: unless-stopped
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: bitcart
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - dbdata:/var/lib/postgresql/data
    expose:
      - "5432"
  backend:
    depends_on:
      - database
    links:
      - database

volumes:
  dbdata:
