services:
  database:
    restart: unless-stopped
    image: pgautoupgrade/pgautoupgrade:17-alpine
    command: ["-c", "random_page_cost=1.0"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: bitcart
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - dbdata:/var/lib/postgresql/data
    expose:
      - "5432"
  backend:
    depends_on:
      - database
    links:
      - database

volumes:
  dbdata:
