services:
  smartbch:
    restart: unless-stopped
    image: bitcart/bitcart-sbch:stable
    environment:
      SBCH_NETWORK: ${SBCH_NETWORK:-mainnet}
      SBCH_SERVER: ${SBCH_SERVER:-https://seed-server.bitcart.ai}
      SBCH_SEED_SERVER: ${SBCH_SEED_SERVER:-https://seed-server.bitcart.ai}
      SBCH_SEED_SERVER_REFRESH_INTERVAL: ${SBCH_SEED_SERVER_REFRESH_INTERVAL:-3600}
      SBCH_DEBUG: ${SBCH_DEBUG:-false}
    expose:
      - "5007"
    volumes:
      - "smartbch_datadir:/data"

  backend:
    depends_on:
      - smartbch
    links:
      - smartbch

volumes:
  smartbch_datadir:
