services:
  smartbch:
    restart: unless-stopped
    image: bitcartcc/bitcart-sbch:stable
    environment:
      SBCH_NETWORK: ${SBCH_NETWORK:-mainnet}
      SBCH_SERVER: ${SBCH_SERVER:-https://smartbch.fountainhead.cash/mainnet}
    expose:
      - "5007"
    volumes:
      - "smartbch_datadir:/data"

  backend:
    depends_on:
      - smartbch
    links:
      - smartbch

volumes:
  smartbch_datadir:
