services:
  store:
    restart: unless-stopped
    image: bitcartcc/bitcart-store:stable
    expose:
      - "3000"
    command: yarn start
    environment:
      BITCART_STORE_API_URL: ${BITCART_STORE_API_URL}
      VIRTUAL_NETWORK: nginx-proxy
      VIRTUAL_PORT: 3000
      VIRTUAL_HOST: ${BITCART_STORE_HOST}
      VIRTUAL_HOST_NAME: "bitcart-store"
      LETSENCRYPT_HOST: ${BITCART_STORE_HOST}
      LETSENCRYPT_EMAIL: ${BITCART_LETSENCRYPT_EMAIL}
      BITCART_STORE_ROOTPATH: ${BITCART_STORE_ROOTPATH:-/}
      BITCART_ADMIN_HOST: ${BITCART_ADMIN_HOST}
      BITCART_ADMIN_ROOTPATH: ${BITCART_ADMIN_ROOTPATH:-/}
