services:
  tor-relay-gen:
    restart: unless-stopped
    image: bitcart/docker-gen:0.9.2
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./torrc-relay.tmpl:/etc/docker-gen/templates/torrc.tmpl:ro"
      - "tor_relay_torrcdir:/usr/local/etc/tor"
    entrypoint: /usr/local/bin/docker-gen -filter-network $<DEPLOYENT_NAME>?_default -notify-sighup $<DEPLOYENT_NAME>?-tor-relay-1 -watch -wait 5s:30s /etc/docker-gen/templates/torrc.tmpl /usr/local/etc/tor/torrc-2
    links:
      - tor-relay
    environment:
      TOR_RELAY_NICKNAME: ${TOR_RELAY_NICKNAME}
      TOR_RELAY_EMAIL: ${TOR_RELAY_EMAIL}

  tor-relay:
    restart: unless-stopped
    image: bitcart/tor:0.4.7.13
    environment:
      TOR_PASSWORD: bitcart
      TOR_ADDITIONAL_CONFIG: /usr/local/etc/tor/torrc-2
    volumes:
      - "tor_relay_datadir:/home/tor/.tor"
      - "tor_relay_torrcdir:/usr/local/etc/tor"
    ports:
      - "9001:9001"
      - "9030:9030"
volumes:
  tor_relay_datadir:
  tor_relay_torrcdir:
