name: Publish

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow_ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/test.yml
    permissions:
      contents: read
      security-events: write # needed for github advanced security
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  demo:
    needs: ci
    name: demo
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      contents: read
      pages: write # to publish on github pages
      id-token: write # OIDC token for pages deployment

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Set up Python
        uses: bitcart/bitcart-actions/actions/setup-python@master

      - name: Install dependencies
        run: |
          uv sync --frozen --compile-bytecode

      - name: Build demo
        run: |
          just build-demo
          mkdir -p site
          cp generator/demo/index.html site/
          cp generator/demo/bitcart_compose_generator-*.whl site/
          echo "generator.bitcart.ai" > site/CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  publish:
    needs: ci
    uses: bitcart/bitcart-actions/.github/workflows/build-docker-image.yml@master
    permissions:
      contents: read
      packages: write # publishing to GHCR
      id-token: write # OIDC for provenance
      attestations: write # github attestations
      artifact-metadata: write # artifact storage metadata (recommended by actions/attest)
    with:
      dockerfile: generator/Dockerfile
      image-name: bitcart/docker-compose-generator
      tags: |
        type=raw,value=latest
      dockerhub-user: ${{ vars.DOCKERHUB_USER }}
    secrets:
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
